---
title: "Intro to Programming"
subtitle: "Session 0 - DEC Python training"
author: "DIME Analytics & DECAT"
institute: "DEC, The World Bank Group"
output:
  xaringan::moon_reader:
    css: [default,default-fonts,custom-css/this-slide.css] 
    lib_dir: libs
    nature:
      ratio: "16:9"
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

---
class: inverse, center, middle

# Intro to session

---
class: middle

## Scope of this session

.pull-left[
  The *DEC Foundations of Python* does not require
  that you have any background in programming. 
  
  If you have no programming background, 
  then this session will prepare you for the rest of the course.
  
  In addition to learning how to write code,
  you also need to learn to approach data work slightly differently.
]

.pull-right[
  **Content of this session:**
  
  1. Why programming? Work flow in data work programming
  
  1. Why Python?
  
  1. How does one write good code?
  
  1. Some common concepts in programming 
]

---
class: middle

## What we assume about you:

Python can be used for many topics in computer science. 
But we must restrict the scope.
We've made these assumptions about you and why you want to learn Python: 

1. You want to use Python for data work (numbers, text data, geo-data etc.), 
as opposed to, developing software, website back-ends etc.

1. You have some experience working with data. 
For example, extensive work in Excel or some work in Stata or R.

---
class: inverse, center, middle

# Why programming? 
# Work flow in data work programming

---
class:  middle

## Why programming? 

.pull-left[

  Data work should be very exact. Computers are more exact than humans.

  Instead of manually working with the data directly, 
  we write code that are instructions for computers to work with the data.
  
  Since computers are very exact, 
  our code becomes an exact record of what was done to the data 
  and how outputs were generated.
]

.pull-right[

]

---
class:  middle

## Compare Excel and programming

  | | Excel | Programming |
  |---------|-----|-----|
  | Are manual edits done directly to the files containing data? | Yes, we manually work directly in the file containing the raw data and and outputs | We only manually edit the code which is a different file from data and output.  |
  | Can we write instructions for the computer to modify our data? | Yes, formulas | Yes, code |
  | Are instructions to modify our data mixed with manual edits? | Yes, it is common | No, that's never the work flow |
  | Do we have an unambiguous way of sharing what was done to the data? | Only formulas are shown, not manual edits | Yes, it is the code |
  | Is it easy for a reviewer to reproduce all steps? | Its challenging or impossible to follow any manual edits as there is no record of them | Yes, anyone who has the code and the access to the input data can reproduce everything |

---
class: middle

## Programming is like writing recepies

.pull-left[
  ### Sponge cake:
  * Set oven on 200C
  * Melt 200g butter and mix with 200g sugar
  * Mix in 4eggs one at the time
  * Mix in 200g flour
  * Bake in the middle of the oven for 30 min
]

.pull-right[
  ### Data science visualization:
  * Get GDP per capita data from for all countries
  * Get investment data from all WB client countries
  * Remove data that was not found in both dataset
  * Sort ascendingly on GDP per capita
  * Export a scatter plot and format the colors and the text
]


---
class: middle

## Data work in programmaing

.pull-left[

* Code should only have well-documented inputs 

* How to document original data:
    * _Primary data_: secure back-up of raw data
    * _Secondary data_: Cite the data source

* Derivatives of original data (new data products and analysis outputs) should be created from original data and code only
  
* Version control your code - Git/GitHub
]

.pull-right[

]


---
class: middle

## Code is how you communcate data science

.pull-left[
  Chefs use recipes to communicate about food, 
  data scientists use code to communicate about data work.
  
  A cook book of poorly written recipes will lead to bad food. 
  The same applies to code and data outputs.
]

.pull-right[PICTURE]




---
class: middle, center

.large[
  .margin-bottom100[
    Code is not just a means to an end - **code is an end in itself**
  ]
  
  The code is a comprehensive and exact method to communicate the project's data work, and **the code is an output** just as much as the project's final report, data visualizations etc.
]


---
class: inverse, center, middle

# Why Python?

---

class: 

## Why Python?


.pull-left[

Why are there so many programming languages? How does Python compare to other languages?

**Free/Open-source**: Python is and will always be 100% free to use

**Easy syntax**: Python code reads more similarly to regular English

**Widely used**: Many users means many user developed tools

**#1 in data science**: The language with most data science tools

**General purpose**: Python can be used for data science, servers, software etc.
]

.pull-right[

]
---
class: middle

## Learn how to commnuicate data science well

.pull-left[
  **Correct code:** Code that generates correct results
  
  **Good code:** Code that can be understood and used by others
]

.pull-right[
  **Code should be both correct code and good code.**
  
  Correct code is really valuable to a team,
  if it can be read and understood by the team members.
  
  Compare this to, for example, a recipe, a driving direction or legal contract,
  that is correct but impossible to read or understand by anyone else.
]


---
class: middle, center

.large[
  .margin-bottom100[
    Code is not just a means to an end - **code is an end in itself**
  ]
  
  The code is a comprehensive and exact method to communicate the project's data work, and **the code is an output** just as much as the project's final report, data visualizations etc.
]



---
class: middle

## The code is an output in itself

Many people new to programming only think of _code as a means to an end_.
Something that give them access to advanced topics like 
regression analysis, machine learning, national language processing etc.

While it is true that code enables you to do advanced things you should consider the **_code as a end in itself_**. Think of code as an output just as much as dashboards, data visualizations etc. are.

Think of **_code as a comprehensive and exact method to communicate_** 
about your work. 
Outputs shared, published etc. together with the code used to generate them
will always be received as more credible.

Results in a research papers without a _theory_/_methods_ section
are often no considered credible results.
Similarly, data work not accompanied with code 
is often not considered credible datawork.


---

## Re-use code

Since the instructions in programming are files 
separate from inputs and outputs, 
we can easier copy instructions across different projects. 

Even if you were to have an exact log of all steps ever done to an Excel file,
it would likely involve a lot of work applying them all to a new file,
and it would be error prone.

Programmers always re-use code across projects.
It is an art to write fully re-usable code 
that require little or no work when re-used across projects.
But it will always be easier and less error prone
than manually copy work in Excel.

Some developers write code which only purpose is 
to be used by other users in their projects.
This is often developed as open-source code packages.
Such code packages are called a "_libraries_" and
there are 1000s of them free to use.
This means that for most purposes 
you do not need to write your code starting from scratch.
You can always build on someone else's efforts.

---
class: middle

## Correct code can still be bad code

Since the code is a central component in both
communication about and collaboration on your work 
it is important that you write good code.
Good code is more than just code that generates correct results.

As an example, have you ever received a letter written by a lawyer
that is difficult to read even though it is very correct?
Or have you ever read a World Bank working paper with
a theory section that is impossible to follow? 
We want to write code that also makes sense to someone 
that has a different skill set.

The peer most likely to benefit from your code being good code
is your future self.
Hastily written code, even when generating correct outputs, is likely to cause you or someone in your team a delay much longer then writing the code well in the first place.

---
class: middle

## How to learn how to write good code

Learn from the beginning how to write good code. 
There are almost always more than one way to solve something in code. 

**Learn from others**. 
Whatever way we recommended in this course 
is often based on  the practice with which we think 
it is the easiest to write good code. 
This is true for most trainings and tutorials you will learn from.

**Review each other's code**. 
The best way to learn about good code and the importance of it
is to review code that has room from improvement.
When you don't understand code, 
pay attention to what is difficult to follow
and ask yourself if you do the same thing.
In addition to being a great learning experience, 
peer-review of your code is a great way for you to improve,
not just your skills,
but also the code that you are contributing to your team.

**Use comments**. Comments is a concept that 
almost all programming languages have.
Comments is a descriptive bit of text in your code file
that is skipped by the computer. 
It's only purpose is to make the code itself easier 
to follow by a human reader.

---

## Summary - key advantages of programming:

**1. Transparency**<br>
You can share your code as a fully transparent log
of everything ever done to the input data.
This log can be shared with others,
but the person likely to benefit from this most frequently is yourself.

**2. Replication**<br>
As the code is a transparent log of what was done to the data,
anyone else who has access to the input data can use your code
and run it to verify that they get the same results as you and your team.
This makes your results more credible
and is becoming a standard requreirment in research.

**3. Re-usability/automation**<br>
We can copy/paste a section of code from one project to another.
Meaning that we can repeat all work on one project to another project
with just some small adjustments. 
Over time we build a toolbox of code sections for tasks we frequently need,
and we will be much more productive.

---
class: inverse, center, middle

# Running code and some common concepts in programming 

---
class: middle

## Code is a file meant to run from top to bottom

.pull-left[
When writing code this is far from always true. 
We manually jump back and forth to solve bugs,
to make the code more readable etc.

But in the end, we want code that does the task correctly when executed from top to bottom
]

.pull-right[
TODO: DIAGRAM WITH BLOCKS THAT REPRESENTS SECTIONS IN CODE
]


---
class: middle

## Repeating parts of the code

.pull-left[
Sometimes we need to repeat a section of the code. 
For example, repeat a section 10 times, 
repeat a section once for each country in the data, 
repeat some code until you found a match in your data. 

Some of these repeats can be implemented manually,
but some cannot, for example when we

In programming these are called loops. 
We will cover how to do them in Python in session 2.
]

.pull-right[
TODO: DIAGRAM WITH BLOCKS THAT REPRESENTS SECTIONS IN CODE WHERE ONE BLOCK IS REPEATED
]

---
class: middle

## Sometimes skipping parts of the code

.pull-left[
Sometimes we need to skip a section of the code.
For example, in some repeats of a group skip some code,
or skip sections that does not apply in code 
meant to be used on different data.

This is particularly important when writing re-usable code.

In programming these are called if-conditions. 
We will cover how to do them in Python in session 2.
]

.pull-right[
TODO: DIAGRAM WITH BLOCKS THAT REPRESENTS SECTIONS IN CODE WHERE ONE BLOCK IS CONDITIONAL
]


---
class: middle

## Sometimes skipping parts of the code

.pull-left[
In the end you have a file where anyone can see exactly what data you used,
what you did to that data,
which values you edited,
what parts you repeated and what parts you skipped,
and finally what outputs were created.

This is fully transparent and therefore much more credible data work.
Someone can also be inspired of or build on your work.
]

.pull-right[
TODO: FINAL DIAGRAM
]

---

class: center, middle

# Thanks!


